dist: bionic
language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
    - ~/.cache
    - ~/.sonar/cache

addons:
  sonarcloud:
    organization: vetrosound
    token:
      secure: RvA2WKVnUYp8NxY0d6Syox3wu3L12UdxYhsj1FifHuAEeArWehn9N2a5kAYlRjdJJ/sjUUC8mok+gmW5GNlyaBaCu5vPI72FMRb2XxecVU77m1ABHDNzk7PyiRMLeHcBvjE3tdlTkWPwws0e/KrWLI8Tz3RPQ3knRsFEKeK3NbD/KyT4THX6oWF34h4PGZJQU4CQWCcmSXteAxUIXtFSuVkkE7EY+XikkspQTn4+Jm7hJi0oyBaPRIrsMIOI3fBXNYvEQKl+7y3sonaDKGcqQ186WBNlHlB9otKkMm8QjdvO2FcyuNRulQn3T23K5QZShdGZMUoZ+Qw8s0Vu1BLc+LqJJaKmscVsHQUJvsj7vTTpXSJVRxYpDflPeKhnF+YoKtNn6B6vVwZFzBfmm1wPp1jhMtqc0jUaGkTi6lWnN+j2y/05CddoOvh9p7odMxHhW17P6FC8PpQ0V4TRlJ/Ug+f/PwSFW5uzuzKZ3F8OQR28tPYt5x7jQuHpZUjFEHJSRA8R6D0ofK2Ig8nLHz18tQjX32+Dobl/NaDRowdHY54C59r35/DPDJCQBudBIx0XBMLx5ZfsAT84pm4sBySJBcTyEeMu/dG9JfZVtpV7sjSpJju+sD+xzFjCnOP87k88WsTUR7PRJD5R1tDhygYMQIfIG0ewVWeOz90h2dKuNRc=

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn lint
  - yarn build
  - yarn test
  - yarn test:e2e
  - sonar-scanner

notifications:
  email: false
  slack:
    on_success: always
    on_failure: change
    rooms:
      - secure: VifPWHmeni0A4RfJxUEdaE+HpmSep4lK883ZYNGXBRwDUJER+gn1AfFyp2a7iQi5OpAyMRiblNBMLpRB8Y7gdezaSL7A+KaWUH7JDSHBperA/fLqzj5smVl/Yi5RFzFStC7raQA00mcLfqEva2fUcg0Q5N6j0uUvDUPS933TKJnbz9YoTbcHEU4uQIZL4UNXet8MX5ahUBSek8NArd/vLfcbUmOwZ5CniNCrebcPW5jUG9Ai94fk4+XzsKO3q8jKU6uy8XG1KMVbJv85M+eQUd8GnTm+mL0xEDAR1oaRI/ZldfszbbffUJuhXTXaz+lkYWueTe0laBhBo+AKX/AWvXDxM1ZmFTxwlxK5sf8LNIfvv/ABAM22wd5XNS4ALLeDT1fX4Z68MyC6YuhNUBY4k25Ud9efSuBRsWcRU3DD6Xk/qhmYLmagmY7DTCLwGc6fJXRXuCb4jCe/nj5aKXffX0ctc6h8D4LrEZ7t6Qs98Jg5G5tvYmDq382Mii8RpFX3jjHZVOHSt3dpflOl6des8ho74uDKMsBicmcr8OPEx6CB5+jcdqri1pYWBC6kLwJvu8NjV4YkLmY/HQE+hZDJR5dbBVb3ifFpwqy7BN8844islVuTkBjwAXyGKw4+rm0/nFNpSmdFJfOU7YjZXr+1XTOTsfGRUTvYCyx0MMjoz1w=
